version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    depends_on:
        - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "Crazybabygirl.87"
        ACCEPT_EULA: "Y"
   
